New Changes
infracloudio/firecracker-marathon pull request #1
Opened 2018-12-26 05:43 UTC by ipochi

Signed-off-by: Imran Pochi <imran@infracloud.io>

2018-12-26 07:07 UTC, sanketsudake requested changes

2018-12-26 07:07 UTC, sanketsudake commented on cmd/main.go
> +	runtime.Start()
Change this to Gateway server start, so that we can go ahead with merge.
For testing purpose, we can write some test script which calls runtime APIs.

2018-12-26 07:07 UTC, sanketsudake commented on gateway/client/client.go
> +package client
We don't need a client for now, can be removed. If needed create  a <project_root/pkg> folder. Move the client under it.

2018-12-26 07:07 UTC, sanketsudake commented on gateway/client/client.go
> +package client
We can introduce cli once everything is working fine

2018-12-26 07:07 UTC, sanketsudake commented on gateway/handler.go
> +
Add http 501*not implemented* in these handlers.

2018-12-26 07:07 UTC, ssudake21 commented on gateway/handler.go
> +	c, err := client.NewClient(defaultHost, apiVersion, "")
Let's call runtime directly for now as discussed

2018-12-26 07:07 UTC, ssudake21 commented on gateway/routes.go
> +		{verb: "GET", path: path("function/{id}", APIVersion), fn: g.getFunction},
Add 
`{verb: "GET", path: path("function", APIVersion), fn: g.getFunctions},`

Should list all existing functions.

2018-12-26 07:07 UTC, ssudake21 commented on how 50c37893f169a534fee07f43242fbebdd883b79e
> +[33mcommit f9f6a17dc2401601925c3d618edec741017bbcab[m[33m ([m[1;36mHEAD -> [m[1;32mmaster[m[33m, [m[1;31morigin/master[m[33m)[m
Remove

2018-12-26 07:07 UTC, ssudake21 commented on man
> +
Remove. Add much needed content in README

2018-12-26 07:07 UTC, ssudake21 commented on runtime/server.go
> +package runtime
Lets go with interfaces only for now. Server we dont need introduce now.
Later on after POC we will write swagger spec for both gateway and runtime and generate code automatically

2018-12-27 05:26 UTC, impochi commented on cmd/main.go
> +	runtime.Start()
this starts the runtime server only. nothing related to gateway

2018-12-27 06:13 UTC, ssudake21 commented on cmd/main.go
> +	runtime.Start()
We need to run way gateway here, not runtime.

2018-12-27 06:15 UTC, sanketsudake requested changes

2018-12-27 06:15 UTC, ssudake21 commented on pkg/gateway/client/client.go
> +package client
Make Client another package. It should not be part of gateway.

2018-12-27 06:22 UTC, sanketsudake approved these changes

2018-12-27 06:23 UTC, merged